# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2VhMmJlZjI5YjNlMDVhOGM0ODhhZTM1YjNiZDc5M2M3YmFlZWEzYjBmZTM2YTE5NWEzZmM0MmE5YjVlNjQxYjVjMzMyYThjYjQ1OTBmNzU4NjJkMzYxOGJlNTY2ZjU3YWMzZTFhODQ4NmMwNzI2ZDY2NjJkMjY4NWZiYWNmODY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
