# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWYwNThmYTU0MTY5NzRlZTAzNjg3YTgxNTVmMzc3MmMxNzUwMDc2ZTI3MjZiMzkzYjA5NGNmNmFlMWU3ZGU5OWI5NTU3MjQ1NjFkMTJhMzdjMjMyZmExN2NiNzhiNmU1OTlhMDlkOTQ2MjgzNTgzYjM3NzNkZGJhODcxYjdlZjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
